### PR TITLE
fix: Error handling for inbound

### LINKED ISSUE #101: CasualMessageListenerImpl  - service call request, handle WorkException
Currently the network connection would be closed.
The client would expect an error ( see ErrorState).

### PR DESCRIPTION
**Pull request by TobiasLeo**
Fixes several possible inbound-issues where exceptions are thrown:
- Service handler throws, make sure a correct error code is set ensuring that some error response is sent to casual.
- CasualServiceCallWork::issueCall throws outside of try, now JCA work listener handles thrown exception.

Both fixes add better error handling and ensure the callee casual domain does not hang waiting for a reply (at least until a timeout is reached).

Refs: #96 #101

### CODE REVIEW

File: casual/casual-inbound/src/main/java/se/laz/casual/jca/inflow/ServiceCallWorkListener.java [hunk 1]
```diff
@@ -93,20 +137,24 @@ private ServiceCallEvent createEvent(CasualServiceCallWork work)
...
                         .withSpanId(spanId.asHex());
-            if(!isTpNoReply)
+            if(!isTpNoReply && workContainsReply(work))
             {
                 CasualServiceCallReplyMessage reply = work.getResponse().getMessage();
+
                 eventBuilder.withUserCode(reply.getUserDefinedCode());
             }
         }
         if(!isTpNoReply)
```
Comment (aliothe) [inline casual/casual-inbound/src/main/java/se/laz/casual/jca/inflow/ServiceCallWorkListener.java:152]: Should not other branch also fail with TPESYSTEM in case there is an exception.
That is, if it is TPNOREPLY and we got an exception - I would expect TPESYSTEM as well.

File: casual/casual-inbound-api/src/main/java/se/laz/casual/jca/inflow/work/CasualServiceCallWork.java [hunk 2]
```diff
@@ -134,6 +135,13 @@ private void issueCall()
                         .setTransactionState( TransactionState.ROLLBACK_ONLY );
             log.warning( ()-> "ServiceHandler not available for: " + message.getServiceName() );
         }
+        catch( Throwable t)
```
Comment (cklellie) [inline casual/casual-inbound-api/src/main/java/se/laz/casual/jca/inflow/work/CasualServiceCallWork.java:145]: Do we also need a similar handling for no reply variant `issueCallNoReply`? In the case where there is a misbehaving service handler which handles a no reply call?

File: casual/casual-inbound/src/main/java/se/laz/casual/jca/inflow/ServiceCallWorkListener.java [hunk 3]
```diff
@@ -58,31 +69,64 @@ public ServiceCallWorkListener(Channel channel, CasualServiceCallRequestMessage
...
+        log.finest(() -> "Work started in %d ms with corrid %s".formatted(e.getStartDuration(), getCasualCorrelationId(getCasualServiceCallWork(e))));
         eventBuilder.start();
     }
 
     @Override
     public void workCompleted(WorkEvent e)
     {
         eventBuilder.end();
-        CasualServiceCallWork work = (CasualServiceCallWork) e.getWork();
+        if (e.getException() != null)
```
Comment (cklellie) [inline casual/casual-inbound/src/main/java/se/laz/casual/jca/inflow/ServiceCallWorkListener.java:114]: Perhaps add a `log.finest` here too similar to in `workStarted`?

File: casual/casual-inbound-api/src/test/groovy/se/laz/casual/jca/inflow/work/CasualServiceCallWorkTest.groovy [hunk 4]
```diff
@@ -253,4 +253,26 @@ class CasualServiceCallWorkTest extends Specification
         then:
         reply.getMessage().getError() == ErrorState.TPENOENT
     }
+
+    def "Call service where service handler throws an exception, returns result with TPESYSTEM status."()
```
Comment (cklellie) [inline casual/casual-inbound-api/src/test/groovy/se/laz/casual/jca/inflow/work/CasualServiceCallWorkTest.groovy:257]: Maybe add a test with no reply variant ensuring noException thrown?

**Review by cklellie — COMMENTED** [review]
Looks really good, just a few bits I have commented on if you could have a look at please.

**Review by aliothe — COMMENTED** [review]
TPNOREPLY with exception, we would want TPESYSTEM in the event for that as well.

**Comment by TobiasLeo** [comment]
> TPNOTRAN with exception, we would want TPESYSTEM in the event for that as well.

@aliothe I'm not sure I understand, where would TPNOTRAN not receive a TPESYSTEM if an unexpected error occurs as opposed to other scenarios?

File: casual/casual-inbound-api/src/main/java/se/laz/casual/jca/inflow/work/CasualServiceCallWork.java (hunk 2 above)
Comment (TobiasLeo) [reply casual/casual-inbound-api/src/main/java/se/laz/casual/jca/inflow/work/CasualServiceCallWork.java:145]: I did this but could only log it as severe. A consequence was the need to introduce a new boolean in the work to flag it as unexpectedly failed to be able to handle the comment @aliothe had about reporting the error code in this event as TPESYSTEM and not OK

File: casual/casual-inbound/src/main/java/se/laz/casual/jca/inflow/ServiceCallWorkListener.java (hunk 3 above)
Comment (TobiasLeo) [reply casual/casual-inbound/src/main/java/se/laz/casual/jca/inflow/ServiceCallWorkListener.java:114]: Added this to ensure parity in logging between the different events

File: casual/casual-inbound-api/src/test/groovy/se/laz/casual/jca/inflow/work/CasualServiceCallWorkTest.groovy (hunk 4 above)
Comment (TobiasLeo) [reply casual/casual-inbound-api/src/test/groovy/se/laz/casual/jca/inflow/work/CasualServiceCallWorkTest.groovy:257]: Added, which also assumes we go with the solution I did now with catching exceptions and logging in TPNOREPLY scenario

**Review by cklellie — APPROVED** [review]
